In [58]:
import sys
import os
import importlib


sys.path.insert(0, "../../src")

import GOSTRocks.metadataMisc as meta

In [51]:
importlib.reload(meta)
in_folder = (
    "/home/wb411133/data/Projects/MR_Novel_Urbanization/Data/LSO_URBAN_DATA_new_naming"
)

make_meta = meta.metadata_gost(in_folder, os.path.join(in_folder, "METADATA"))
layers = make_meta.get_layers()
metadata = make_meta.generate_metadata()

Could not import arcgis libraries

In [56]:
# Make changes to the metadata table here, if you want; changes can be made to resulting xls file later
metadata["metadata"].sort_values(["folder", "layer_name"])

,layer_name,data_type,crs_name,crs_code,num_dimensions,min_lon,max_lon,min_lat,max_lat,vector_shape_type,vector_object_count,folder,raster_width,raster_height,raster_res,layer_label,description,source_name,source_url,data_process_summary
6,lso1k_gpo,Raster,World_Mollweide,NaN,1,2.483000e+06,2.713000e+06,-3.723000e+06,-3.475000e+06,NaN,NaN,,248.0,230.0,1000.000000,,,,,
9,lso_adm,Raster,World_Mollweide,NaN,1,2.483000e+06,2.713000e+06,-3.722750e+06,-3.475750e+06,NaN,NaN,,988.0,920.0,250.000000,,,,,
13,lso_cpo15,Raster,WGS 84,4326.0,1,2.702958e+01,2.946542e+01,-3.066875e+01,-2.857208e+01,NaN,NaN,,2516.0,2923.0,0.000833,,,,,
14,lso_cpo20,Raster,WGS 84,4326.0,1,2.702958e+01,2.946542e+01,-3.066875e+01,-2.857208e+01,NaN,NaN,,2516.0,2923.0,0.000833,,,,,
15,lso_des,Raster,WGS 84,4326.0,1,2.702222e+01,2.947222e+01,-3.067500e+01,-2.856667e+01,NaN,NaN,,759.0,882.0,0.002778,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34,urban1k_pop,Raster,World_Mollweide,NaN,1,2.483000e+06,2.713000e+06,-3.723000e+06,-3.475000e+06,NaN,NaN,/FINAL_STANDARD_1KM,248.0,230.0,1000.000000,,,,,
52,urban_pop,Raster,World_Mollweide,NaN,1,2.483000e+06,2.713000e+06,-3.723000e+06,-3.475000e+06,NaN,NaN,/FINAL_STANDARD_1KM,248.0,230.0,1000.000000,,,,,
0,lso1k_adm,Vector,WGS 84,4326.0,13,2.702458e+01,2.947025e+01,-3.067282e+01,-2.856812e+01,Polygon,1.0,NaN,NaN,NaN,NaN,,,,,
2,lso_adm,Vector,WGS 84,4326.0,13,2.702458e+01,2.947025e+01,-3.067282e+01,-2.856812e+01,Polygon,1.0,NaN,NaN,NaN,NaN,,,,,
1,lso_adm,Vector,WGS 84,4326.0,13,2.702458e+01,2.947025e+01,-3.067282e+01,-2.856812e+01,Polygon,1.0,NaN,NaN,NaN,NaN,,,,,

In [17]:
make_meta.write_metadata?

In [59]:
make_meta.write_metadata(
    os.path.join(in_folder, "METADATA", "metadata.xlsx"),
    layer_metadata=metadata["metadata"],
)

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

# Debugging